"""Documented decision taxonomy for the assessment layer (prompt 24 §2).

Two orthogonal vocabularies:

* DECISION STATES — the evidentiary strength of a conclusion. Deliberately NOT a
  SAFE/UNSAFE verdict and NEVER an exploitability judgement.
* CONCLUSION TYPES — what the conclusion is about (finding / CVE / runtime /
  native / remediation / assessment-level).

Every mapping below is explicit and inspectable. There are no weights, no ML, no
probabilities, and no "risk of exploit".
"""

from __future__ import annotations

# --- decision states (evidentiary strength) --------------------------------
CONFIRMED = "CONFIRMED"
STRONGLY_SUPPORTED = "STRONGLY_SUPPORTED"
SUPPORTED = "SUPPORTED"
CONDITIONALLY_SUPPORTED = "CONDITIONALLY_SUPPORTED"
REQUIRES_REVIEW = "REQUIRES_REVIEW"
UNVERIFIED = "UNVERIFIED"
BLOCKED = "BLOCKED"
INCONCLUSIVE = "INCONCLUSIVE"
NOT_APPLICABLE = "NOT_APPLICABLE"
SUPERSEDED = "SUPERSEDED"

DECISION_STATES = (
    CONFIRMED, STRONGLY_SUPPORTED, SUPPORTED, CONDITIONALLY_SUPPORTED, REQUIRES_REVIEW,
    UNVERIFIED, BLOCKED, INCONCLUSIVE, NOT_APPLICABLE, SUPERSEDED,
)

# Deterministic display / precedence ordering (strongest evidentiary standing
# first). Precedence never implies "more dangerous" — only "more evidence".
DECISION_ORDER = {s: i for i, s in enumerate(DECISION_STATES)}

# States that mean a human still needs to look / evidence is missing.
OPEN_STATES = {REQUIRES_REVIEW, UNVERIFIED, BLOCKED, INCONCLUSIVE, CONDITIONALLY_SUPPORTED}
# States that are evidentiarily settled (either supported or not-applicable).
SETTLED_STATES = {CONFIRMED, STRONGLY_SUPPORTED, SUPPORTED, NOT_APPLICABLE, SUPERSEDED}

# --- conclusion types ------------------------------------------------------
# finding
FINDING_CONFIRMED = "FINDING_CONFIRMED"
FINDING_SUPPORTED = "FINDING_SUPPORTED"
FINDING_UNVERIFIED = "FINDING_UNVERIFIED"
FINDING_BLOCKED = "FINDING_BLOCKED"
FINDING_INCONCLUSIVE = "FINDING_INCONCLUSIVE"
# cve
CVE_CONFIRMED = "CVE_CONFIRMED"
CVE_POSSIBLY_RELEVANT = "CVE_POSSIBLY_RELEVANT"
CVE_VERSION_UNVERIFIED = "CVE_VERSION_UNVERIFIED"
CVE_NOT_AFFECTED = "CVE_NOT_AFFECTED"
CVE_NOT_REACHABLE = "CVE_NOT_REACHABLE"
CVE_EVIDENCE_INSUFFICIENT = "CVE_EVIDENCE_INSUFFICIENT"
# runtime
RUNTIME_CORROBORATED = "RUNTIME_CORROBORATED"
RUNTIME_NOT_OBSERVED = "RUNTIME_NOT_OBSERVED"
RUNTIME_UNAVAILABLE = "RUNTIME_UNAVAILABLE"
RUNTIME_MOCKED_ONLY = "RUNTIME_MOCKED_ONLY"
# native
NATIVE_API_CONFIRMED = "NATIVE_API_CONFIRMED"
NATIVE_PATH_CORROBORATED = "NATIVE_PATH_CORROBORATED"
NATIVE_REACHABILITY_UNVERIFIED = "NATIVE_REACHABILITY_UNVERIFIED"
NATIVE_ANALYSIS_UNAVAILABLE = "NATIVE_ANALYSIS_UNAVAILABLE"
# remediation
REMEDIATION_RECOMMENDED = "REMEDIATION_RECOMMENDED"
REMEDIATION_CONDITIONAL = "REMEDIATION_CONDITIONAL"
REMEDIATION_REQUIRES_REVIEW = "REMEDIATION_REQUIRES_REVIEW"
REMEDIATION_REMEDIATED = "REMEDIATION_REMEDIATED"
REMEDIATION_STATUS_UNVERIFIED = "REMEDIATION_STATUS_UNVERIFIED"
# assessment-level
SECURITY_RELEVANT_EVIDENCE_PRESENT = "SECURITY_RELEVANT_EVIDENCE_PRESENT"
SECURITY_REVIEW_REQUIRED = "SECURITY_REVIEW_REQUIRED"
EVIDENCE_INCOMPLETE = "EVIDENCE_INCOMPLETE"
VALIDATION_INCOMPLETE = "VALIDATION_INCOMPLETE"
ASSESSMENT_CONCLUSIVE = "ASSESSMENT_CONCLUSIVE"
ASSESSMENT_INCONCLUSIVE = "ASSESSMENT_INCONCLUSIVE"

# --- subject types (reference existing entities; never duplicated) ----------
SUBJECT_FINDING = "FINDING"
SUBJECT_CVE = "CVE"
SUBJECT_RUNTIME = "RUNTIME"
SUBJECT_NATIVE = "NATIVE"
SUBJECT_REMEDIATION = "REMEDIATION"
SUBJECT_ASSESSMENT = "ASSESSMENT"

# --- source evidence layers ------------------------------------------------
LAYER_FINDINGS = "FINDINGS"
LAYER_CVE = "CVE"
LAYER_VALIDATION = "VALIDATION"
LAYER_REMEDIATION = "REMEDIATION"
LAYER_RUNTIME = "RUNTIME"
LAYER_NATIVE = "NATIVE_DEEP"
LAYER_OBFUSCATION = "OBFUSCATION"
LAYER_ATTACK_SURFACE = "ATTACK_SURFACE"
LAYER_REACHABILITY = "REACHABILITY"
LAYER_ROOT_CAUSE = "ROOT_CAUSE"
LAYER_DIFF = "DIFF"
LAYER_INVESTIGATION = "INVESTIGATION"

# evidence mode — kept distinct exactly as prior layers do.
MODE_STATIC = "STATIC"
MODE_LIVE = "LIVE"
MODE_MOCKED = "MOCKED"
MODE_UNAVAILABLE = "UNAVAILABLE"
